stages:
  - validate
  - deploy

validate_infra:
  stage: validate
  script:
    - opentofu fmt -check
    - opentofu validate

deploy_libvirt:
  stage: deploy
  script:
    - opentofu apply -auto-approve -var="environment=dev" -var="provider=libvirt"
  only:
    - main
